apiVersion: v1
kind: Namespace
metadata:
  name: acme-air-gcp
spec:
  finalizers:
  - kubernetes
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    category: database
    app: mongodb
  name: mongodb
  namespace: acme-air-gcp
spec:
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      affinity: {}
      containers:
      - name: mongodb
        image: mongo:3.2
        imagePullPolicy: Always
        args:
          - mongod
          - --storageEngine
          - wiredTiger
          - --smallfiles
          - --noprealloc
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        ports:
        - containerPort: 27017
          name: connection-port
          protocol: TCP
        resources: {}
        securityContext:
          capabilities: {}
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/db
          name: acme-air-gcp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  volumeClaimTemplates:
  - metadata:
      name: acme-air-gcp
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
      storageClassName: pks-default
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: mongodb
  name: mongodb
  namespace: acme-air-gcp
spec:
  clusterIP: None
  ports:
  - name: connection-port
    port: 27017
    protocol: TCP
    targetPort: connection-port
  selector:
    app: mongodb
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: acme-web 
  name: acme-web
  namespace: acme-air-gcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acme-web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: acme-web
    spec:
      affinity: {}
      containers:
      - args:
        - npm
        - start
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: PORT
          value: "3000"
        - name: MONGO_HOST
          value: mongodb
        - name: MONGO_PORT
          value: "27017"
        image: garreeoke/acmenode:1
        imagePullPolicy: Always
        name: acme-web
        ports:
        - containerPort: 3000
          name: http-port
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http-port
        readinessProbe:
          httpGet:
            path: /
            port: http-port
        resources: {}
        securityContext:
          capabilities: {}
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: acme-web
  name: acme-web
  namespace: acme-air-gcp
spec:
  ports:
  - name: http-port
    port: 3000
    protocol: TCP
  selector:
    app: acme-web
  sessionAffinity: None
  type: LoadBalancer
